### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by arademaker** [kraison/vivace-graph-v3#25] opened 2019-02-05 10:11 UTC
SBCL 1.4.16 on MacOS

```
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "MREMAP" not found in the OSICAT-POSIX package.
;   
;       Line: 151, Column: 33, File-Position: 5176
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /Users/ar/quicklisp/local-projects/vivace-graph-v3/mmap.lisp" {100C1D3FB3}>

```

**Comment by kraison** [comment] 2019-02-05 11:05
See issue #22:

"The call to mremap is necessary in order to extend memory mapped files when space is low.  It is possible to do the same thing by calling munmap / mmap, but you would probably need additional locks to ensure that bad things didn't happen to threads that were in the middle of writing to the mapped file.  Otherwise, there may be other incompatibilities with OSX;  no efforts have been made to date to support it.  If you would like to contribute a patch, please feel free!"

**Comment by kraison** [comment] 2019-02-05 11:08
Closing as duplicate of #22

**Closed** 2019-02-05 11:08 UTC
